title: Do more than you think
author:
  name: Mr. Tang
  email: 879767200@qq.com
  
description: >
  Write an awesome description for your new site here. You can edit this line
  in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.

# theme: minima

remote_theme: https://github.com/niklasbuschmann/contrast
#StartBootstrap/startbootstrap-clean-blog-jekyll
# vszhub/not-pure-poole
# ngzhio/jekyll-theme-hamilton

remote_theme: niklasbuschmann/contrast

plugins:
  - jekyll-remote-theme
