title: Do more than you think
author:
  name: Mr. Tang
  email: 879767200@qq.com
  
description: >
  Write an awesome description for your new site here. You can edit this line
  in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.

# theme: minima

remote_theme: "jeffreytse/jekyll-theme-yat"
#StartBootstrap/startbootstrap-clean-blog-jekyll
# vszhub/not-pure-poole
# ngzhio/jekyll-theme-hamilton

plugins:
  - jekyll-remote-theme
