title: Do more than you think

baseurl: "https://tang88-pro.github.io"

description: 业精于勤荒于嬉；行成于思毁于随。

lang: en-US

theme: minima
#remote_theme: "mmistakes/minimal-mistakes@4.26.2"

#plugins:
#  - jekyll-include-cache
