title: Do more than you think

baseurl: ""
url: "https://tang88-pro.github.io"

description: 业精于勤荒于嬉；行成于思毁于随。

lang: en-US

#theme: minima
theme: minimal-mistakes-jekyll

codeminimal_mistakes_skin: "air"
