title: Do more than you think
description: 业精于勤荒于嬉；行成于思毁于随。
baseurl: ""
url: "https://tang88-pro.github.io"

theme: minimal-mistakes-jekyll

codeminimal_mistakes_skin: "air"
locale: "en-US"
subtitle: "Version 2.0"
