title: Do more than you think

description: 业精于勤荒于嬉；行成于思毁于随。

lang: en-US

remote_theme: benbalter/retlab

plugins:
  - jekyll-remote-theme

defaults:
-
  scope:
    path: ""
    type: "posts"
  values:
    layout: post
    comments: true
-
  scope:
    path: ""
    type: "pages"
  values:
    layout: page
    comments: false
