theme: minimal-mistakes-jekyll
codeminimal_mistakes_skin: "air"

locale: "en-US"
title: Do more than you think
subtitle: "Version 2.0"
name: "test name"
description: 业精于勤荒于嬉；行成于思毁于随。
baseurl: ""
url: "https://tang88-pro.github.io"

masthead_title: "My Custom Title"
